"""Emit SQL that seeds hubsync.event_map from the marketing events already
in the HubSpot portal.

    python scripts/event_map_seed.py              # SQL to stdout
    python scripts/event_map_seed.py --out seed.sql

READ ONLY. It lists HubSpot marketing events and prints INSERT statements.
It executes nothing: Carl runs SQL in TablePlus.

What it includes, and what it refuses to touch
----------------------------------------------
Only events whose externalEventId starts with 'csuite-' — the convention this
sync owns. The portal holds three other marketing events that must never
enter event_map, measured 2026-10-06:

  * two from **Eventbrite** (appInfo id 28564), externalEventId
    '1611602760239' and '1587977957819'. A different integration owns them.
  * one with **no externalEventId at all** and no appInfo, created by hand in
    the HubSpot UI: "AMCF Women's Giving Circle - Winter Nominee Meet-up".
    There is no CSuite event date to map it to.

A row in event_map is an instruction to a sync that writes. Seeding one of
those three would hand this job authority over a record it did not create.

Why the seeded content_hash is a sentinel
-----------------------------------------
plan() decides create vs update vs unchanged like this: an event present in
the HubSpot listing is never a create; it is `unchanged` when the seeded
content_hash equals the freshly computed one, and an `update` otherwise. The
11 events in the portal were written by an older sync with known-wrong start
times — three have the wrong time and one the wrong date entirely — so
`unchanged` would be the one wrong answer, and it would be a silent one.

So the seeded hash is the literal string below, which is not a sha256 digest
and therefore cannot collide with a real one. NULL would also mismatch, but
NULL is what a half-repaired row looks like; a sentinel says why it differs.
It is deliberately not hash-shaped, so nobody can mistake it for a
measurement.

Status is 'pending' — "mapped and queued; no HubSpot write has succeeded yet",
which is true of this sync. 'synced' would claim HubSpot matches a hash we
sent, and we have never sent one.

Note that the seed is not required for correctness: plan() already adopts an
event that is in HubSpot but not in event_map ("already in HubSpot, not in
event_map — adopting it"), which is also an update. The seed makes the
adoption explicit and gives the map a hubspot_event_id before the first run,
so a later disappearance from the portal surfaces as `review` — "event_map has
a HubSpot id but HubSpot does not list that externalEventId" — instead of
looking like a brand-new event.
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from clients.hubspot import HubSpotClient  # noqa: E402
from sync import event_hubspot as eh  # noqa: E402

# Not a sha256 digest, on purpose. See the module docstring.
SEEDED_HASH = "seeded-from-portal-never-matches-a-computed-hash"
SEEDED_STATUS = "pending"


def quote(value) -> str:
    """A SQL literal. Single quotes doubled; None becomes NULL."""
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def csuite_events(hubspot):
    """(rows, skipped, error). Only 'csuite-' externalEventIds."""
    index, _calls, error = eh.hubspot_index(hubspot)
    if error:
        return [], [], error

    rows, skipped = [], []
    for external, record in sorted(index.items()):
        if external.startswith(eh.EXTERNAL_PREFIX):
            rows.append((external, record))
        else:
            skipped.append((external, (record.get("appInfo") or {}).get("name")))
    return rows, skipped, None


def statements(rows) -> list:
    """One INSERT per row, idempotent on the unique csuite_eventdate_id."""
    lines = []
    for external, record in rows:
        eventdate_id = external[len(eh.EXTERNAL_PREFIX):]
        lines.append(
            "INSERT INTO hubsync.event_map (csuite_eventdate_id, "
            "hubspot_event_id, external_event_id, content_hash, status) "
            f"VALUES ({quote(eventdate_id)}, "
            f"{quote(record.get('objectId'))}, {quote(external)}, "
            f"{quote(SEEDED_HASH)}, {quote(SEEDED_STATUS)}) "
            "ON CONFLICT (csuite_eventdate_id) DO NOTHING;")
    return lines


def render(rows, skipped) -> str:
    out = [
        "-- hubsync.event_map seed, generated by scripts/event_map_seed.py",
        "-- READ-ONLY generator. Review, then run it yourself.",
        f"-- {len(rows)} marketing event(s) with a '{eh.EXTERNAL_PREFIX}' "
        "externalEventId.",
        f"-- externalAccountId in use: {eh.EXTERNAL_ACCOUNT_ID}",
        "--",
        f"-- content_hash is the sentinel {SEEDED_HASH!r}, which is not a",
        "-- sha256 digest and so cannot equal a computed one. That makes the",
        "-- first run classify every seeded row as an UPDATE rather than",
        "-- `unchanged` — which matters, because the start times these events",
        "-- already carry are known to be wrong.",
        "",
    ]
    if skipped:
        out.append("-- NOT seeded, deliberately — this sync does not own them:")
        for external, app in skipped:
            out.append(f"--   externalEventId={external!r} "
                       f"app={app or 'none (created by hand)'}")
        out.append("")
    out.append("BEGIN;")
    out.extend(statements(rows))
    out.append("COMMIT;")
    out.append("")
    return "\n".join(out)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default=None, help="Write the SQL here.")
    args = parser.parse_args(argv)

    rows, skipped, error = csuite_events(HubSpotClient())
    if error:
        print(f"HubSpot marketing events could not be listed: {error}",
              file=sys.stderr)
        return 1
    if not rows:
        print("No 'csuite-' marketing events found. Nothing to seed.",
              file=sys.stderr)
        return 1

    sql = render(rows, skipped)
    if args.out:
        with open(args.out, "w", encoding="utf-8") as handle:
            handle.write(sql)
        print(f"{len(rows)} row(s) written to {args.out}", file=sys.stderr)
    else:
        print(sql)
    print("Nothing was executed. Run it yourself after reviewing.",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
